name: Build and Push Flask App Image to Google Cloud Platform
on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vto-docker-image-latest
      PROJECT_ID: virtual-try-on-420112
      LOCATION: northamerica-northeast2-docker.pkg.dev
      CLOUD_RUN_SERVICE: vto-docker-image-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure GCP credentials
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.VTO_SECRETS }}"

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
  
    - name: 'Use gcloud CLI'
      run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: gcloud auth configure-docker $LOCATION --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |
        docker tag $IMAGE_NAME:latest $LOCATION/$PROJECT_ID/vto-artifact/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest $LOCATION/$PROJECT_ID/vto-artifact/$IMAGE_NAME:$GIT_TAG
        docker push $LOCATION/$PROJECT_ID/vto-artifact/$IMAGE_NAME:latest
        docker push $LOCATION/$PROJECT_ID/vto-artifact/$IMAGE_NAME:$GIT_TAG

    - name: Deploy and Update Traffic
      run: |
        gcloud run deploy $CLOUD_RUN_SERVICE \
          --image=$LOCATION/$PROJECT_ID/vto-artifact/$CLOUD_RUN_SERVICE@sha256:f85e525d8384d78b80267ffa2d3bd2125fa7cab95fce4039f724b20ebc72eb46 \
          --region=northamerica-northeast2 \
          --project=$PROJECT_ID
        && gcloud run services update-traffic vto-docker-image-latest --region=northamerica-northeast2 --to-latest
      