name: Build and Push Flask App Image to Google Cloud Platform
on:
  push:
    branches: [main]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vto-image
      PROJECT_ID: virtual-try-on-420112

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure GCP credentials
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/177200455350/locations/global/workloadIdentityPools/vto-pool/providers/vto-github'
        service_account: 'vto-github-action-service@virtual-try-on-420112.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
  
    - name: 'Use gcloud CLI'
      run: 'gcloud auth list --filter=status:ACTIVE --format="value(account)"'
  
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:1.0 ./vto

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker northamerica-northeast2-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:1.0 northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/vto-artifact/$IMAGE_NAME:tag1
        docker push northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/vto-artifact/$IMAGE_NAME:tag1

    # docker pull us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
    # docker tag us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0 us-central1-docker.pkg.dev/virtual-try-on-420112/quickstart-docker-repo/quickstart-image:tag1
    # docker push us-central1-docker.pkg.dev/virtual-try-on-420112/quickstart-docker-repo/quickstart-image:tag1

    # docker pull us-central1-docker.pkg.dev/virtual-try-on-420112/quickstart-docker-repo/quickstart-image:tag1
